### ISSUE TITLE
Consulta sobre politicas de contraseñas

### ISSUE THREAD

**Issue by chdiaz11** [fernandoing/aprende_aws#2]
Qué pasa si cambio la política de contraseñas a 15 caracteres y existen cuentas que no la cumplen, se les bloquea la cuenta o la política le aplica cuando cambien su nueva contraseña?

**Comment by fernandoing** [comment]
Que tal @chdiaz11.
Según la documentación de AWS, los cambios se aplicarian a la proxima vez que los usuarios tengan que reinicar su contraseña.

> 
> When you create or change a password policy, most of the password policy settings are enforced the next time your users change their passwords. However, some of the settings are enforced immediately. For example:
> 
> When the minimum length and character type requirements change, these settings are enforced the next time that your users change their passwords. Users are not forced to change their existing passwords, even if the existing passwords do not adhere to the updated password policy.
> 
> When you set a password expiration period, the expiration period is enforced immediately. For example, assume that you set a password expiration period of 90 days. In that case, the password expires for all IAM users whose existing password is older than 90 days. Those users are required to change their password the next time that they sign in.
> 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_account-policy.html

**Comment by fernandoing** [comment]
Si no tienes más dudas, sientete libre de cerrar el ticket.

**Comment by chdiaz11** [comment]
Muchas gracias!!!
