### ISSUE TITLE
Permiso administrativo completo ...

### ISSUE THREAD

**Issue by penny1mx** [fernandoing/aprende_aws#3]
Hola a todos buenos días,

Tengo una pregunta, dentro de los permisos totales o iguales a la cuenta root es la llamada:

AdministratorAccess

Adiciono una captura de pantalla para mejor referencia.

![AdministratorAccess](https://user-images.githubusercontent.com/85125281/120222807-2b7aea00-c206-11eb-8a74-af92802a966b.JPG)

Mi pregunta puntual, si un usuario tiene esta política aplicada es igual al usuario que se genera desde un inicio con AWS ( es decir el root ) ???

Muchas gracias !!!

**Comment by fernandoing** [comment]
Hola!
Muchas gracias por utilizar Github para publicar tu duda.

Como podras leer en la [documentación](https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/access_policies_job-functions.html#jf_administrator). Esta politica otorga a cualquier usuario control sobre todos los servicios y recursos dentro de tu cuenta de AWS.

Con esto dicho, un usuario con "AdministratorAccess" (llamemoslo **admin**) no tiene los mismo privilegios que el usuario root.
El usuario root puede entrar a la sección de Billing y los reportes de costos desde el principio, pero es necesario agregar políticas adicionales para que un **admin** pueda ver los detalles de costos. Te dejo el [link](https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/tutorial_billing.html).
Adicional, hay algunas cosas miselaneas que un **admin** no puede realizar como:
* El usuario root no puede ser borrado por un **admin** ya que el usuario root no aparece en IAM.
* Se necesita ser root para poder borrar una cuenta de AWS.
* Se necesita ser root para manejar AWS organizations.
* Y deben de haber más pero quizás no me las he topado.

Espero y esta información te pueda ser útil.
Saludos!

**Comment by penny1mx** [comment]
Wow, muchísimas gracias por tu respuesta tan rápida.

Te pongo un poco en contexto, quiero dejar de ocupar el usuario Root, y delegar este permiso ( completo ) a un par de usuarios con nombre y apellido, para esto requeriría que los dos usuarios tengan los permisos mas parecidos al usuario Root, es decir que prácticamente puedan hacer todo dentro de la cuenta de AWS.

He agregado ya el permiso de Billing, conoces algún otro que tenga que agregar para que contemple lo que te comento ???

![AdministratorAcess](https://user-images.githubusercontent.com/85125281/120228707-51f25280-c211-11eb-8294-59bd943ac9c7.JPG)

Muchas gracias.

Saludos cordiales.

**Comment by fernandoing** [comment]
Hola de nuevo.

Para un uso del día al día, debería de bastar con estos dos permisos (Billing y adminAccess).
Pero si encuentras que hay algo que no puedes hacer sin tener que agregar alguna política adicional, no dudes en actualizar este ticket para compartir el conocimiento.

Saludos!

**Comment by penny1mx** [comment]
Por su puesto !!!

Cuenta con ello, valdria mucho la pena algun video que onde un poco mas en politicas, por lo demas excelente !!!

Saludos cordiales.
