### ISSUE TITLE
Github etiquetas ...

### ISSUE THREAD

**Issue by penny1mx** [fernandoing/aprende_aws#4]
Hola buenos días,

Este es mas bien un problema que quiero reportarte, en uno de tus videos mencionaste el que cada vez que coloquemos un nuevo ticket coloquemos etiquetas a los mismos.

Revisando no es posible ya que no aparece ninguna disponible:

![Label](https://user-images.githubusercontent.com/85125281/120223104-ab08b900-c206-11eb-917f-2404987d9f7c.JPG)

Tenemos que hacer algo adicional para que puedan aparecer ???

Muchas gracias.

Saludos cordiales.

**Comment by fernandoing** [comment]
Hola, buenos días.
Una disculpa, en Github se llaman labels. 
Te mentiría si supiera como se llaman en español. Pero espero y te sea útil!

**Comment by penny1mx** [comment]
Si, de hecho se llaman igual "labels", mas bien mi pregunta es que no aparecen.

Esos tu los darás de alta ??? Te lo pregunto por que en el video mencionaste que lo haríamos nosotros cada que coloquemos un nuevo ticket.

Esto solo es como comentario, es decir no podemos agregar etiquetas o labels.

Saludos cordiales.
