### ISSUE TITLE
S3 - Encripcion y velocidad ...

### ISSUE THREAD

**Issue by penny1mx** [fernandoing/aprende_aws#5]
Hola como estas !!!

De nuevo molestandote, en el video llamado "Aprender AWS desde cero - 05 - Seguridad en S3 (Acceso y Encriptado)", diste una muy buena explicacion del tema de encripcion.

Pero me surgio una duda al momento de encriptar ya sea un objeto o bien la bucket entera me imagino trae un efecto negativo al acceder al objeto o bien la bucket por el tema de velocidad en la desecripcion de la misma.

Haz tenido alguna queja con respecto a esto ???

Un ejemplo seria encriptando un objeto luego este colocandolo publico, imagino cuando lo acceden tendria que desencriptarse para mostrarlo ( esto cuando realizan una consulta ), que tan negativo resulta esta encripcion ???

Muchas gracias !!!

Y como siempre muchas gracias por trabajar de esa manera !!!

Saludos cordiales ...

**Comment by fernandoing** [comment]
Que tal @penny1mx.
Así como lo supones, hay un limite contra el que te podrías topar cuando utilizando KMS para encryptar/desencryptar archivos de s3.

Puedes revisar los limites para cada caso individual por región acá:
https://docs.aws.amazon.com/es_es/kms/latest/developerguide/requests-per-second.html

Pero en resumen, estas limitado a 5,500 operaciones por segundo (depende de la región).
Espero y esto te sea útil.
Saludos!

**Comment by penny1mx** [comment]
Excelente !!!

Muchisimas gracias por la respuesta tan rapida y efectiva ...
