### ISSUE TITLE
Dudas sobre las AMI

### ISSUE THREAD

**Issue by victormanuelac** [fernandoing/aprende_aws#6]
Hola, primero deseo agradecer lo mucho que tu canal me ha enseñado de AWS.

Tengo una duda, en el capítulo "Aprender AWS desde cero - 09 - EC2- Iniciamos nuestra primera instancia EC2" mencionas las AMI, pero no haces ninguna referencia a costos, y he visto versiones incluso hasta con software que son free que tienen un costo por hora, ¿a qué se debe ese costo? ¿es una licencia por uso? E incluso, ¿en las AMI de software privativo (WIndows server, por ejemplo) cubre el costo de la licencia?

**Comment by fernandoing** [comment]
Hola, una disculpa por la demora.
Los costos del marketplace dependeran del provedor de la AMI.
https://aws.amazon.com/marketplace/features/custom-terms-pricing/

Se puede establecer un contrato con ellos para lograr diferentes precios, pero no es algo manejado por AWS.

La razon de la demora es que me he estado enfocando en el servidor de discord que creo y es un mejor lugar para resolver este tipo de dudas.

Te dejo la liga por si te quieres unir:

Discord:
https://discord.gg/YN8VRpM6Av
